### ISSUE TITLE
Query logging prints binary data and long arrays, flooding stdout

### ISSUE THREAD

**Issue by niieani** [mikemintz/rethinkdb-websocket-server#8]
When `unsafelyAllowAnyQuery` is on, rethinkdb-websocket-server prints every query with **all of its data** to the console. This includes `r.binary()` stuff like uploaded files and arrays with binary data (say, when storing UInt8Arrays in the DB as a part of the object). A couple of megabytes sent to stdout can really cause havoc. I think the data should be trimmed in the output after an X number of characters, plus there should be an option to turn off showing queries altogether. There are legitimate use cases for not using any validation and running the server, e.g. when running unit tests that should bypass validation or when running the server locally and just wanting to connect to the server instance from a web page, with full control.

**Comment by mikemintz** [comment]
@niieani That's a really good point. It actually logs all queries even when `unsafelyAllowAnyQuery` is off, but it logs twice for queries not in the whitelist. I punted on this before, since I wasn't sure whether it made sense to start adding additional complexity, or to depend on an actual logging framework like winston.

I think it makes sense to keep things simple, but at least add a `logIncomingQueries` option that defaults to true for backwards compatibility.

What would you think of trimming the argument to `r.binary()` in log output, as opposed to trimming the entire query? I think it's important that developers can see the entire incoming query in order to write a whitelist rule for it, but the binary arguments (or potentially string arguments to other terms) doesn't always need to be fully displayed.

**Comment by niieani** [comment]
Yeah, I agree with trimming individual data arguments - not only r.binary but also strings and long arrays. I think the first 30 chars should be enough to still be able to make sense of the query, and not too long so that the whole query won't fit on screen.
I think it would be good to have 3 modes:
1. no logging at all - totally silent
2. some logging - display queries which were not whitelisted after trimming internal arguments; for queries which are whitelisted simply acknowledge the fact that a query has happened (something like **$DATE - ALLOWED A WHITELISTED QUERY**)
3. full logging - show all queries, internal arguments trimmed to 30 chars

I think the 2nd mode makes most sense to run in production, while the 3rd in development, and 1st is good for unit testing where we don't care about permissions.
It would also make sense to log whitelisted queries to `stdout`, while those not whitelisted to `stderr`. It will make it easier to make a sort of `access.log` and `error.log` out of the output by redirecting those two outputs to different files.

**Comment by mikemintz** [comment]
I added three logging modes in 0.3.4, `all` to log everything (default behavior), `denied` to only log queries that don't match the whitelist, and `none` for silent (other than exceptions).

This should allow debugging / verbose logging with the default options, but allow production runs where you only see unexpected behavior.

This was more of a quick fix, but I think if we want to make things more flexible and distinguish access logs from error logs, we should start using an actual logging framework.

Regarding the argument trimming, there are currently two ways the queries are been printed out.
1. We always log the reql toString() representation, which always outputs r.binary as `r.binary(<data>)`, and if it's important to truncate string arguments, we'd have to submit a PR to rethinkdb itself since the function is in their javascript driver.
2. We log the AST representation of queries that don't pass the whitelist. This is probably where you're seeing the binary data being output. I think I'll probably remove this logging altogether in the next version, since we'll deprecate that whitelist syntax in favor of vanilla syntax.

**Comment by niieani** [comment]
Great stuff Mike! I think you're right about the 2nd point, regarding AST representation and `r.binary`.
